# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true

# Plugins
modmuss50_mod_publish_version        = 0.8.4
fabric_loom_version                  = 1.16.3

# Common
java_version                         = 25
minecraft_version                    = 26.2

# NeoForge
loader_version_range                 = [4,)
minecraft_version_range              = [26.2, 26.3)
neo_moddev                           = 2.0.141
neo_version                          = 26.2.0.1-beta
neo_version_range                    = [21,)

# Fabric
fabric_version                       = 0.158.0+26.2
fabric_loader_version                = 0.19.3

# Libs
azurelib_version                     = 4.0.0-alpha.14

# Mod options
group                                = mod.azure.azexamples
mod_name                             = AzureLib Examples
mod_author                           = AzureDoom, Boston
mod_id                               = azexamples
mod_license                          = MIT
mod_description                      = AzureLib Examples
mod_credits                          = AzureDoom, Boston
mod_logo                             = icon.png
mod_url                              = https://github.com/AzureDoom/Azurelib-Rewrite-Examples
mod_issues                           = https://github.com/AzureDoom/Azurelib-Rewrite-Examples/issues
mod_sources                          = https://github.com/AzureDoom/Azurelib-Rewrite-Examples
version                              = 1.0.0
