# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = false
org.gradle.jvmargs                   = -Xmx3G

# Plugins
parchment_minecraft                  = 1.18.2
parchment_version                    = 2022.11.06

# Common
java_version                         = 17
minecraft_version                    = 1.18.2

# NeoForge
loader_version_range                 = [40,)
mapping_channel                      = official
mapping_version                      = 1.18.2
minecraft_version_range              = [1.18.2, 1.19)
neo_version                          = 40.3.0
neo_version_range                    = [40.3,)

# Fabric
fabric_version                       = 0.77.0+1.18.2
fabric_loader_version                = 0.17.2

# Libs
modmenu_version                      = 3.2.5
azurelib_version                     = 3.1.11

# Mod options
group                                = mod.azure.azexamples
mod_name                             = AzureLib Examples
mod_author                           = AzureDoom, Boston
mod_id                               = azexamples
mod_license                          = MIT
mod_description                      = AzureLib Examples
mod_credits                          = AzureDoom, Boston
mod_logo                             = icon.png
mod_url                              = https://github.com/AzureDoom/Azurelib-Rewrite-Examples
mod_issues                           = https://github.com/AzureDoom/Azurelib-Rewrite-Examples/issues
mod_sources                          = https://github.com/AzureDoom/Azurelib-Rewrite-Examples
version                              = 1.0.0
