plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'com.diffplug.spotless'
}

neoForge {
    version = "${neo_version}"
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            this.file('runs/server').createParentDirectories()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "mod.azure.azurelib:azurelib-neo-${minecraft_version}:${azurelib_version}"
}
